### ISSUE TITLE
Ontology PURL is 404

### ISSUE THREAD

**Issue by SArndt-TIB** [PlantPhenoOntology/ppo#103]
Hi everyone,

I face the problem, that the ontology PURL does not resolve (any longer?).
I wanted to retrieve an RDF serialization with http://purl.obolibrary.org/obo/ppo.owl.
This directs me to this: https://raw.githubusercontent.com/PlantPhenoOntology/ppo/master/releases/2018-10-26/ppo.owl but this is 404 (and also not the latest release either). 
This is probably the correct file? https://raw.githubusercontent.com/PlantPhenoOntology/ppo/refs/tags/v2018-10-26/releases/2018-10-26/ppo.owl - but again, there is a more recent release.

Looks like the configuration needs to be updated, the targets on GitHub are no longer reachable: https://github.com/OBOFoundry/purl.obolibrary.org/blob/master/config/ppo.yml

Thanks for looking into this!

Susanne

**Comment by anitacaron** [comment]
To complement, when you changed the default branch to `main`, you also need to update the purl configuration 😄

**Comment by ramonawalls** [comment]
Sorry it interfered with your work, but I'm happy to see that someone outside our internal group noticed! I hope to have the obo foundry purl redirect corrected within the next day.

**Comment by SArndt-TIB** [comment]
Thanks for fixing @ramonawalls :-)
