### ISSUE TITLE
implement trait sketch

### ISSUE THREAD

**Issue by stuckyb** [PlantPhenoOntology/PPO#17]
We sketched out a diagram (will be attached below) of how traits can be implemented using pairs of data properties on "count" quality classes to bound numerical data values, along with present/absent convenience classes.

**Comment by rlwalls2008** [comment]
![img_7756](https://cloud.githubusercontent.com/assets/3310510/18759064/7c975e5c-8096-11e6-878d-d54c3d634e3e.JPG)
![img_7755](https://cloud.githubusercontent.com/assets/3310510/18759065/7ce773ba-8096-11e6-85db-1ea7dc691df4.JPG)

**Comment by rlwalls2008** [comment]
There's also this:
![img_7750](https://cloud.githubusercontent.com/assets/3310510/18759082/8bd3f146-8096-11e6-8f4a-40a2ab95362f.JPG)

**Comment by stuckyb** [comment]
Perfect -- thanks, @rlwalls2008!

**Comment by stuckyb** [comment]
In subsequent discussions, the class structure has changed so that the above diagrams no longer reflect the design of the PPO.  Nevertheless, the basic ideas expressed in these diagrams have now been implemented.
