### ISSUE TITLE
Revised definitions for intial growth stages

### ISSUE THREAD

**Issue by ramonawalls** [PlantPhenoOntology/PPO#19]
The definition csv files aren't editable in Excel, and the format made my head spin when I tried to edit them in TextWrangler, so I am pasting my definition suggestions here for you, @stuckyb. 

The following two stages are the same (as suggested by the fact that there is a single subclass for PPO:0000005.  We should merge them into one class. I suggest keeping PPO:0000018 and making it a direct subclass of initial growth stage (PPO:000020).

PPO:0000005, initial growth during first growth cycle phenological stage: An {initial growth phenological stage} in which some participant plant is in its {initial growth cycle}. 
>>delete. We don't need to obsolete, because it was never released.

PPO:0000018, emergence during first growth cycle phenological stage: An {initial growth phenological stage} in which some participant plant is in an {initial growth cycle} and has completed the {seed germination stage} but the plant has not yet produced a {true leaf}. 
>>Need to add to logical definition that the plant is participating in the initial growth cycle.

Revise the following definition and add a comment:
PPO:0000007, emergence during later growth cycle phenological stage: An {initial growth during later growth cycle phenological stage} in which some participant plant is an herbaceous perennial plant, all living plant structures produced during earlier growth cycles are below ground, and a plant structure that started growth during the current growth cycle is visible above the ground but has not yet produced a {true leaf}. 
>>Add a comment: This stage applies only to herbaceous perennials that die back above ground between growth cycles and resprout from below ground meristems or buds.

PPO:0000009, new green shoots sprouting from nodes on existing above-ground stems phenological stage stage: An {initial growth during later growth cycle phenological stage} in which some participant plant has new growth visible on an existing above-ground {shoot system} that did not originate from buds.
>>Add a comment: This stage follows a dormant stage and occurs only to plants that break dormancy from meristems that are not parts of buds.

PPO:0000017, bud burst phenological stage: An {initial growth during later growth cycle phenological stage} in which some participant plant is a woody plant that has at least one {vegetative bud} in the {bud burst stage}.
>>Add a comment: This stage follows a dormant stage and occurs only to plants that break dormancy from buds.

**Comment by stuckyb** [comment]
I've implemented everything here except for the changes to 'initial growth during first growth cycle phenological stage' and its subclass 'emergence during first growth cycle phenological stage'.  Do we really want to delete the first of these two?  The reason I defined it in the first place is so that we had a logical counterpart to 'initial growth during later growth cycle phenological stage'.  It is true that at the moment, 'initial growth during first growth cycle phenological stage' has only a single subclass, but keeping it in the ontology means that we have the logical framework in place for defining *other* 'initial growth during first growth cycle phenological stage's if the need ever arises.  For that reason, might it make sense to leave it in the PPO?

**Comment by robgur** [comment]
I'd vote to leave it in.

**Comment by rlwalls2008** [comment]
I don't know. I can't think of a case when where there is initial growth during the first cycle other than after germination (at least for seed plants). If we move into in vitro cultivation or non-seed plants (mosses or ferns), we will need other terms, but the PO already covers those pretty well, and I doubt if many people are collecting phenology data on moss spore germination or fern embryo development. At this point, as we don't have any need for the class, I think it just represents one more term for users to have to sift through to find what they want, so I recommend removing it. 

Does @robgur have an opinion? We can also run this by Ellen and Kjell.

**Comment by robgur** [comment]
I can see the point if it is going to cause confusion but generally agree
with Brian's view that it might be a stub to add classes that seem
logically consistent with placement in PPO.
-r

**Comment by ramonawalls** [comment]
FYI, I don't feel strongly about this, and I understand why you want to leave it in.

**Comment by stuckyb** [comment]
I'm considering this closed, then, since there is not strong consensus to eliminate the parent class.  This question could be revisited in the future if it becomes and issue.
