### ISSUE TITLE
new label for ripe fruit

### ISSUE THREAD

**Issue by ramonawalls** [PlantPhenoOntology/PPO#21]
As it is defined as a fruit that is participating in a fruit ripening stage, a better label would be "ripening fruit".

**Comment by ramonawalls** [comment]
Also, can you add an axiom that PO:plant structure is a subclass of BFO:material entity? I think we may get some reasoning conflicts later if not.

**Comment by stuckyb** [comment]
Regarding the second comment (superclass of PO:plant structure), would it make more sense to put that relationship in the PO, not the PPO?

**Comment by ramonawalls** [comment]
Re. fruit ripening: I think the reason PO does not have a stage for ripe fruit is precisely because it is so hard to define when a fruit is "ripe". One could define objective criteria for ripeness in individual species or cultivars, but not across all angiosperms. Even though NPN records that fruit is "ripe", it is still legitimate for us to use a more broad term and say that the fruit is ripening (i.e. participating in a fruit senescence process). Calling the entity a "ripening fruit" probably provides the broadest compatibility.

**Comment by ramonawalls** [comment]
Re. superclass for plant structure: Yes, technically, it should be in the PO. It is implied by the reference to the CARO terms anatomical structure (which is a structure with mass and therefore a material entity). CARO is no longer active, so the full logical definitions are not likely to be added there, and PO is not going to add them any time soon. 

The reason I suggested adding it is so that when we talk about an observing process, a plant structure can be the material target of observation. However, we probably don't actually need it in PPO. If we do encounter problems with inference, we can add the relation to the application ontology, which allows PPO to stay more broadly interoperable.

Should have put this in it's own ticket, but I think we can "close" this part of the discussion here and take it up in another ticket if it comes up again.

**Comment by stuckyb** [comment]
Re. fruit ripening:  That makes sense, Ramona.  I've made all of the changes to the relevant stage and trait classes.  Should we do the same thing for "ripe seed cone"?

Re. superclass for plant structure:  Sounds good.  We'll consider this closed until it becomes and issue.

**Comment by ramonawalls** [comment]
I find it odd to refer to the ripening process for a cone, as ripening is defined as fruit senescence, but a  quick search suggests that people do use the term. However, it will have to mean something different that fruit ripening. Maturation and mature would be better terms, but that's outside the scope of PPO. So, yes, I think you should change the label to "ripening seed cone".

**Comment by stuckyb** [comment]
Okay, done.  I think this issue can now be closed.
