### ISSUE TITLE
def. of later growth cycle and exit from dormancy

### ISSUE THREAD

**Issue by ramonawalls** [PlantPhenoOntology/ppo#24]
Current definition: A plant growth cycle (PPO:0000200) that begins with exit from dormancy (GO:0097438).

It occurs to me that this could cause problems, because seed germination is the exit from seed dormancy. Sometimes, the embryo itself (the whole plant we are interested in) is dormant before germination, so technically seed germination can also involve and exit from dormancy of the whole plant. How hard would it be to write the definition to say that it begins with exit from dormancy after a dormant period after an initial growth cycle?

**Comment by ramonawalls** [comment]
I'd suggest rephrasing the definition to:

"A 'plant growth cycle' (PPO:0000200) that begins with 'exit from dormancy' (GO:0097438) of the participating plant. This cycle cannot begin with the exit from dormancy of a seed.

The equivalency axiom ['plant growth cycle' and ('starts with' some 'exit from dormancy')] should be sound, because plant growth cycle is a whole plant development stage and whole plant development stage has a whole plant (not a seed or other structure) as primary participant. However, the PO definition of whole plant development stage is weak, so it is likely that instance seed germination stages would in fact be inferred to be instances of later growth stage. Therefore, I recommend that we change the equivalency axiom to a subclass axiom to be on the safe side. It is weak, but we don't currently have a use case where we need to make inferences based on growth cycles.

@stuckyb, let me know if you see any problems with these proposed changes.

**Comment by stuckyb** [comment]
@ramonawalls, I think your changes make sense.  Your comments make me wonder, though, if our definition of 'initial growth cycle' is invalid.  We have: "A {plant growth cycle} that begins with {seed germination}."  But, it sounds like 'plant growth cycle' (which is a 'whole plant development stage') cannot actually begin with 'seed germination'?

**Comment by ramonawalls** [comment]
No, I think we are okay, @stuckyb. The parent class, 'plant growth cycle' can begin with either germination  or exit from dormancy of the whole plant, while as the two child classes begin with either seed germination (for initial growth cycle) or exit from dormancy (for later growth cycle). However, I we probably need to be more specific in our definition of later growth cycle. Rather than just saying that is starts with exit from dormancy, we should say that it starts with exit from dormancy of some whole plant.
