### ISSUE TITLE
rename this repo

### ISSUE THREAD

**Issue by ramonawalls** [PlantPhenoOntology/ppo#25]
Can we please rename this repo to ppo (lower case)? It is really annoying to have the capps. I would do it myself, but I don't want to mess up anything in your build system, @stuckyb.

**Comment by stuckyb** [comment]
Yes, it is fine to rename it.  It shouldn't cause any problems, but we will need to update IRIs for the ontology entities.  I was going to rename it myself, but I don't seem to have the required permissions.

**Comment by ramonawalls** [comment]
Thanks,  Brian. I'll take care of renaming the repo this week. Let me know if you want me to fix the IRIs. I'll fix the PURLs too.

**Comment by ramonawalls** [comment]
Done. Everyone, beware that there is now a different path to PPO (although github does redirect). @jdeck88 and @stuckyb, take note!

**Comment by ramonawalls** [comment]
Updated PURL.
