### ISSUE TITLE
PPO purl needs to be updated

### ISSUE THREAD

**Issue by jdeck88** [PlantPhenoOntology/PPO#26]
Going to http://purl.obolibrary.org/obo/ppo.owl

redirects to:
https://raw.githubusercontent.com/PlantPhenoOntology/PPO/master/ontology/ppo.owl

however, that file does not exist anymore.  The redirect should goto:
https://raw.githubusercontent.com/PlantPhenoOntology/PPO/master/ontology/ppo-raw.owl

I'm putting Ramona's name on this task as she setup the purl... not sure else has access.

**Comment by ramonawalls** [comment]
I fixed it. I'm happy to keep doing this, but the other option is for others to fork the purl repo (https://github.com/OBOFoundry/purl.obolibrary.org), make the changes, and then do a pull request on this file: https://github.com/OBOFoundry/purl.obolibrary.org/blob/master/config/ppo.yml.

Might take a little while for the redirect to work.
