### ISSUE TITLE
Condense the PPO top-level hierarchy

### ISSUE THREAD

**Issue by ramonawalls** [PlantPhenoOntology/ppo#29]
We should specify some superclasses for some of the imported terms. If we are going to include BFO in our hierarchy, we might as well put everything there that fits. Here is my list of suggestions, with the rationale:

PO:plant structure dev. stage subClassOf BFO:occurent - This is the intent of the PO, and it's a pretty low bar in terms of commitment.

UBERON:processual entity subClassOf BFO:occurent - This is actually stated in the definition.

PO:plant structure subClassOf BFO:material entity - You can trace its definition back to CARO:material anatomical entity.

GO:biological process subClassOf BFO:process - This is the intention of GO.

PATO:quality will have to stay where it is for now.

**Comment by stuckyb** [comment]
Totally agree with this, @ramonawalls.  I will need to add a feature to OntoPilot that allows spreadsheet rows to modify existing ontology entities (rather than exclusively creating new ones).  Once that is done, these changes should be trivial.

**Comment by stuckyb** [comment]
@ramonawalls, I believe I have all of these changes implemented as you specified.  When you have a chance, could you verify that the top-level structure matches what you had in mind?

**Comment by ramonawalls** [comment]
This is done. @stuckyb added a term file called import_extensions.ods.
