### ISSUE TITLE
Finish FIMS mapping of classes/annotation properties

### ISSUE THREAD

**Issue by jdeck88** [PlantPhenoOntology/PPO#3]
1. create species annotation property on plant
2. make phenological stages as classes, currently they are annotation properties
3. Add qualities "e.g. <3  breaking leaf buds"

These need to be added to the FIMS ppo_config.xml file.

**Comment by rlwalls2008** [comment]
Closing this. We have an initial set of mappings, but we have instead come up with a workflow for mapping spreadsheets using tools being developed under #biocode-fims-configurator
