### ISSUE TITLE
Definition of 'plant phenological stage'

### ISSUE THREAD

**Issue by stuckyb** [PlantPhenoOntology/ppo#31]
As currently defined: "A 'spatiotemporal region' (BFO:0000011) that encompasses some part of the life of a 'whole plant' (PO:0000003) or a population of plants and is part of a 'plant growth cycle' (PPO:0000200)."

I think we should remove "or a population of plants" from this definition.  This language is not repeated in any of the other stage definitions, and I don't think it is accurate.  All of our traits and stages are defined in terms of parts of a single plant.  If someone wants to describe the phenology of a population, it can be done by describing the phenological stages of the *members* of the population.

What do others think?

**Comment by robgur** [comment]
+1

**Comment by ramonawalls** [comment]
In response to @stuckyb 's comment above: I agree that we can remove the word population from the text definitions. However, I think it is important that a population still be able to participate in a plant phenological stage, as long as one of its members is participating in the stage. We need to be able to say this for the NPN data where they score stages for clumps of plants (i.e. populations). 

Didn't we have a call at one of our meeting where we discussed with @jdeck88 a way to parse whether or not the bearer of a phenological trait was a plant or a population, provided the row includes that data?

**Comment by ramonawalls** [comment]
See also discussion of proposed definitions in #16. 

'spatiotemporal region' THAT 'has participant' SOME (
'whole plant' THAT 'participates in' SOME 'plant growth cycle'
)

**Comment by ramonawalls** [comment]
Here is where we discussed how to disambiguate whole plants from populations: https://github.com/jdeck88/pheno_paper/issues/27
