### ISSUE TITLE
Add comment to senescent leaf stage

### ISSUE THREAD

**Issue by ramonawalls** [PlantPhenoOntology/ppo#33]
http://purl.obolibrary.org/obo/PPO_0000013

Add comment:

Leaf color is often used as an indicator of the senescent leaf stage, but note that leaf coloration due to photoprotection (http://amigo.geneontology.org/amigo/term/GO:0010117) is not an indicator of senescence.

**Comment by ramonawalls** [comment]
@stuckyb Is there a way to include a term from GO that is not imported into PPO in the comment? I want to say in the comment "Leaf color is often used as an indicator of the senescent leaf stage, but note that leaf coloration due to {photoprotection} is not an indicator of senescence" but since photoprotection is not imported into PPO, not sure what will happen. Maybe we should just import the class for reference.

**Comment by stuckyb** [comment]
Comment references will only work for terms in the ontology or its 
imports closure (for now, anyway).  So, we'd need to add photoprotection 
to the list of terms imported from the GO.  And I agree, might not be a 
bad idea to import it anyway.

**Comment by ramonawalls** [comment]
Okay, thanks. I'll add it and rebuild the imports.

**Comment by ramonawalls** [comment]
go_ppo_imports.csv has been edited but new import file has not been built yet.
