### ISSUE TITLE
fix definitions of percent data properties

### ISSUE THREAD

**Issue by ramonawalls** [PlantPhenoOntology/PPO#34]
Fix the definitions of lower percent (PPO_0001002) and upper percent (PPO_0001003) so that they give the range of 0-100 instead of 0-1.

**Comment by stuckyb** [comment]
@ramonawalls, that should already be fixed.  See issue #31.  Let me know if you are not seeing the changes for some reason.

**Comment by ramonawalls** [comment]
It's fixed. Closing.
