### ISSUE TITLE
Definition of true leaf, expending leaf, mature leaf

### ISSUE THREAD

**Issue by ramonawalls** [PlantPhenoOntology/ppo#37]
From Ellen:

Almost all of the presence and absence class definitions for vegetative stages include mention of a {true leaf} which is defined as a vascular leaf that is not a cotyledon. We need to modify this somehow, either by changing the definition of {true leaf}, or by adding an additional word/phrase in the present/absent class definitions to indicate that this leaf is not just a non-cotyledon vascular leaf, but also "unfolded" in the sense that the whole length of the leaf is visible, not just the tip. This holds for NPN as well as BBCH (10-19) phenophases (right, Kjell?). I think the only difference is that NPN indicates visibility of the petiole while BBCH does not, and I am fine with glossing over the petiole issue and just indicating that the whole leaf blade or the whole length of the leaf (or whatever wording seems appropriate) has become visible.

**Comment by ramonawalls** [comment]
The issue here is not the presence or absence of a true leaf, but rather its stage. A true leaf is present whenever there is a vascular leaf that is not a cotyledon, regardless of the stage it is in. The problem is that we map NPN "leaves present" to the presence of a true leaf, when in fact we need to map it to the presence of a true leaf in the post-expansion (mature) stage. I would recommend making the trait and stage definitions more specific, rather than changing the definition of true leaf. Suggested changes to follow.

**Comment by ramonawalls** [comment]
The other issue here is that NPN separates leaves into "young leaves" and "leaves", rather than "expanding leaves" and "mature leaves", as the PO does.  

NPN definitions:
young leaf (tree/shrub): A leaf is considered "young" and "unfolded" once its entire length has emerged from a breaking bud, stem node or growing stem tip, so that the leaf stalk (petiole) or leaf base is visible at its point of attachment to the stem, but before the leaf has reached full size or turned the darker green color or tougher texture of mature leaves on the plant. 

young leaf (forb): A leaf is considered "young" before it has reached full size or turned the darker green color or tougher texture of mature leaves on the plant. Do not include fully dried or dead leaves.

It is accurate to say that all young leaves (sensu NPN) are expanding leaves (sensu PO), but one cannot say that all "leaves" (sensu NPN) are post-expansion leaves (sensu  PO) because post-expansion leaves includes leaves that are fully expanded but not yet fully mature.

I think the best way to address this is to make a new class for mature leaf stage, which will be a subclass of post-expansion stage. We can request that PO pick it up. I'll have to do a little research into how to define accurately mature, but we can get the term up there for now so we can proceed.

**Comment by ramonawalls** [comment]
For completeness, and also to accurately define new above ground shoot systems (see issue #xx) we would need to also define a class for those leaves that are fully expanded but not yet fully mature.

**Comment by robgur** [comment]
Good solution.  Is Ellen subscribed to the github repo so she can follow?

**Comment by ramonawalls** [comment]
Not yet, but I have asked her to get an account so I can tag her.

**Comment by edenny** [comment]
So the problem I was bringing up was not about expanding vs. mature, but rather "unfolding" vs. "unfolded". As such, this might be your use case for issue#40.

"Leaves" includes leaves that are unfolded, expanding, post-expansion and mature, but does NOT include that stage before the first true leaf from the bud is in the process of "unfolding".

"Young leaves" includes leaves that are unfolded and expanding, but not mature, and as with "Leaves", not that stage before the first true leaf from the bud is in the process of "unfolding". Thus this phase overlaps with "Leaves" until all leaves on the plant are in post-expansion. (BTW, we only use this phase for evergreen and drought-deciduous plants which might have leaves on the tree all year long, so as to distinguish the period of active leaf growth.)

There is that situation we discussed earlier for drought-decid plants were expansion is completed but maturing is not, which maybe is what you were getting at here. It's ok with me if we overlook that distinction and just map "Young leaves" to leaves before the post-expansion stage.

**Comment by ramonawalls** [comment]
@edenny, you are right that your comment I copied into the first comment above deals with unfolding versus unfolded leaves. However,  if I understood the situation correctly, there was also an issue with young leaves. NPN young leaves includes both expanding leaves and fully expanded leaves that have not yet developed the color or toughness of mature leaves. For this reason, in order to accurately define young leaves, we need to distinguish between expanded but not mature leaves versus mature leaves.

**Comment by edenny** [comment]
Yes, fine with me if we want to formalize that distinction!

**Comment by ramonawalls** [comment]
New classes to create:
stages:
vascular leaf expanded but not mature stage: A {vascular leaf post-expansion stage} that begins when the {vascular leaf} is fully expanded and ends with the onset of the {vascuar leaf mature stage}.

vascular leaf mature stage: A {vascular leaf post-expansion stage} that begins when the {vascular leaf} has turned the darker green color or tougher texture of mature leaves  and ends with the onset of the {vascular leaf senescence stage}.

traits:
expanded but not mature leaf presence: A {plant phenological trait} that is measured by the number of {true leaves} on a {whole plant} that are in the {vascular leaf expanded but not mature stage}.

mature leaf presence (revise current def): A 'plant phenological trait' (PPO:0002001) that is measured by the number of true leaves (PPO:0000209) on a 'whole plant' (PO:0000003) that are in the {vascular leaf mature stage}.

plus corresponding present and absent classes

**Comment by ramonawalls** [comment]
Once all the traits are in place, will need update the phenological stages:

mature leaf phenological stage (update current def): A {non-senescing leaf phenological stage} in which some participant plant has at least one {vascular leaf} in the {vascular leaf mature stage}.

young leaf phenological stages (new term): A {non-senescing leaf phenological stage} in which some participant plant has at least one {vascular leaf} in the {vascular leaf expansion stage} or {vascular leaf expanded but not mature stage}.

plus corresponding logical definitions.

**Comment by ramonawalls** [comment]
All that is left to do is to remake the ontology, but first I have to switch back to java 8. Will do that after dinner then close this issue.

**Comment by ramonawalls** [comment]
We still need classes that map to NPN:leaves, which includes PPO:young leaves and PPO:mature leaves, but not unfolding leaves. 

I also realize that it is not enough to have a class for "young leaf phenological stage. We score the data by traits and then make inferences about stages, so we need to specifically have a trait for young leaf presence, and then define the stage based on that, at least for the NPN mappings.

Will add the following classes:
young leaf presence: A {plant phenological trait} that is measured by the number of true leaves {$true leaf} on a {whole plant} that are in the {vascular leaf unfolded expanding stage} or {vascular leaf expanded not mature stage}.
-plus present/absent classes
-need to fix definition of young leaf phenological stage - it has {vascular expansion stage} or {vascular leaf expanded not mature stage}, which is wrong.

unfolded leaf presence: A {plant phenological trait} that is measured by the number of true leaves {$true leaf} on a {whole plant} that are in the {vascular leaf unfolded expanding stage} or {vascular leaf post-expansion stage}.
-plus present/absent classes

unfolded leaf phenological stage: A {non-senescing leaf phenological stage} in which some participant plant has at least one {vascular leaf} in the {vascular leaf unfolded expanding stage} or {vascular leaf post-expansion stage}.

**Comment by edenny** [comment]
Or can we create yet another class that includes senescing and non-senescing?

**Comment by ramonawalls** [comment]
Based on @edenny 's last comment, we should change the definitions of the unfolded leaf terms to include senescing leaves:

unfolded leaf presence: A {plant phenological trait} that is measured by the number of true leaves {$true leaf} on a {whole plant} that are in the {vascular leaf unfolded expanding stage}, {vascular leaf post-expansion stage}, or {vascular leaf senescent stage}.
-plus update present/absent classes

unfolded leaf phenological stage: A {non-senescing leaf phenological stage} in which some participant plant has at least one {vascular leaf} in the {vascular leaf unfolded expanding stage}, {vascular leaf post-expansion stage}, or {vascular leaf senescent stage}.

**Comment by stuckyb** [comment]
That last definition doesn't work because the class now includes senescing leaves, so it can no longer be a subclass of 'non-senescing leaf phenological stage'.  Should this be a subclass of 'vascular leaf phenological stage'?

**Comment by ramonawalls** [comment]
Yes, that was an oversight. Unfolded leaf phenological stage should indeed be a subclass of vascular leaf phenological stage.
