### ISSUE TITLE
Clarify end of bud burst stage

### ISSUE THREAD

**Issue by ramonawalls** [PlantPhenoOntology/ppo#38]
From Ellen: Unclear end of Bud burst stage: For {bud burst stage}, when this stage ends is left ambiguous. I think this is a PO term so we can't change it, but it would be nice to add a note/comment in the ontology, perhaps for the {bud burst phenological stage}, indicating that we consider the bud break stage to end on a bud when the first {true leaf} is unfolded.
---------
PO defines breaking bud stage as "A shoot system development stage (PO:0025527) during which a shoot system (PO:0009006) emerges from the bud (PO:0009006)," which, as Ellen says, is not specific about the start and end. Because NPN's definition is narrower, it fits within this. We should add a comment to clarify how we are using it for NPN, but I don't think we need to create a separate term.

**Comment by ramonawalls** [comment]
Current comment: This stage follows a dormant stage and occurs only to plants that break dormancy from buds.

New comment: This stage follows a dormant stage and occurs only in plants that break dormancy from buds. For USA-NPN data, the bud burst phenological stage ends when the first {true leaf} to emerge from the bud is unfolded.

**Comment by edenny** [comment]
sound good!

**Comment by ramonawalls** [comment]
Has already been fixed.
