### ISSUE TITLE
Check definition of new above ground shoot borne shoot system

### ISSUE THREAD

**Issue by ramonawalls** [PlantPhenoOntology/ppo#39]
Comment from Ellen: New above-ground shoot-borne system: This supporting class is defined as "... does not yet have any true leaves in the {vascular leaf post-expansion stage}." I think it should rather say that it does not yet have any true leaves that are "unfolded" (or whatever language we use for the issues #37 and #40) in order to fit in with the {new above-ground shoot-borne system presence}, right? As written it indicates none of the leaves are mature yet which is a much later point in time.

The goal here is to describe a shoot system that matches NPN's definition of initial growth, which is "Growth is considered "initial" on each bud or shoot until the first leaf has fully unfolded."

The current definition of new above ground shoot-borne shoot system is "An 'above-ground shoot-borne shoot system' (PPO:0000207) that does not yet have any true leaves in the 'vascular leaf post-expansion stage' (PO:0001053)." 

The issue here is that there may be leaves that are unfolded but not yet fully expanded, so the PPO description is broader than the NPN description. This means that our mapping of NPN to the PPO stage is correct, if not very precise. In order to make it more precise, we would have to define new subclasses for expanding leaves that include unfolding and unfolded. I will make a separate issue for that.

**Comment by ramonawalls** [comment]
Please do not put comment on this issue about the relative merits of having separate classes for unfolding and unfolded leaves. Those comments should go on issue #40. This issue is reserved for new above ground shoot-borne shoot system and its mapping to NPN.

**Comment by edenny** [comment]
Roger!

**Comment by edenny** [comment]
Yes, as I see it, it maps ok when "Initial growth" is present. The problem is that it does not map ok when "initial growth" is recorded as absent. After it ends by the NPN definition, there is still quite a bit of time for leaves to be expanding before it ends by this ontology definition.

**Comment by ramonawalls** [comment]
We are currently mapping NPN initial growth (in grasses and forbs) to PPO:new above ground shoot borne shoot system presence. This still needs work.

**Comment by ramonawalls** [comment]
Based on our review of initial growth (which goes until the first true leaf is unfolded), if we change the definition of "new above ground shoot-borne shoot system" to the following, it will fit within the NPN definition of initial growth:
New def: An 'above-ground shoot-borne shoot system' (PPO:0000207) that does not yet have any true leaves in the 'vascular leaf unfolded expansion stage' (PPO:0000226).

That will cover initial growth from existing above ground shoots, and includes bud-burst.
