### ISSUE TITLE
NTR: new growth presence - initial growth

### ISSUE THREAD

**Issue by ramonawalls** [PlantPhenoOntology/ppo#41]
We currently have a class for new above ground shoot-borne shoot system, but we need the more general class for presence of initial (i.e. new) growth that encompasses both seedlings and growth during a later cycle. This would correspond to the initial growth phenological stage. NPN does not ask observers to distinguish between seedlings and new growth from existing plants.

Here are the NPN definitions of initial growth:

Forbs: New growth of the plant is visible after a period of no growth (winter or drought), either from above-ground buds with green tips, or new green or white shoots breaking through the soil surface. Growth is considered "initial" on each bud or shoot until the first leaf has fully unfolded. For seedlings, "initial" growth includes the presence of the one or two small, round or elongated leaves (cotyledons) before the first true leaf has unfolded.

Grasses/sedges: New growth of the plant is visible after a period of no growth (winter or drought), either as new green shoots sprouting from nodes on existing stems,  new green shoots breaking through the soil surface, or re-greening of dried stems or leaves. For each shoot, growth is considered "initial" until the first leaf has unfolded or has fully re-greened.

I don't actually see a class in the NPN mappings for initial growth for woody plants. Presumably this corresponds to bud burst.

**Comment by ramonawalls** [comment]
Before I propose a definition for this, I need to know if it needs to encompass initial growth on both woody and vegetative plants.

**Comment by edenny** [comment]
You are correct that "Initial growth" was created as the equivalent of "Breaking leaf buds" for plants without leaf buds. "Initial growth" is NOT a phenophase used for woody plants, only for forbs and graminoids. HOWEVER, it is sometimes ambiguous whether to place a species in a forb or tree/shrub/subshrub protocol. If the plant has no aboveground woody parts, we give it a forb protocol. Such is the case with Cornus canadensis. I think there are a few other plants we have that are what you'd call "corner cases" and we can safely ignore them. Bottom line--our "Initial growth" phenophase is for non-woody plants.

**Comment by ramonawalls** [comment]
Another issue here is that 'new above ground shoot-borne shoot system presence' could apply to either woody or herbaceous plants. Although PO:bud is a sister to PO:shoot-borne shoot system, there are no restrictions that say you could have a shoot-borne shoot system that is also a bud. We have only mapped new above ground shoot-borne shoot system presence to herbaceous plants, so I suggest that we be explicit and state this in the definition. For now this will just be in text, because we aren't ready to add taxon restrictions just yet.

**Comment by stuckyb** [comment]
Our current definition for 'initial growth phenological stage' is:  

> A 'plant phenological stage' (PPO:0000001) in which some participant plant is in a 'plant growth cycle' (PPO:0000200) and has at least one 'vegetative shoot system' (PO:0025607) that has not yet produced a 'true leaf' (PPO:0000209).

Could we use the latter part of that as the basis for the new class Ramona is proposing?  I realize it is broader than NPN's use of "initial growth" (and not quite congruent since it uses leaf presence instead of leaf unfolding), but maybe broader is okay?  We are certainly making similar compromises with other mappings.

**Comment by ramonawalls** [comment]
Based on our review of initial growth (which goes until the first true leaf is unfolded), if we change the definition of "new above ground shoot-borne shoot system" so that it ends when leaves are unfolded, it will fit within the NPN definition of initial growth:
New def: An 'above-ground shoot-borne shoot system' (PPO:0000207) that does not yet have any true leaves in the 'vascular leaf unfolded expansion stage' (PPO:0000226).
That will cover initial growth from existing above ground shoots, and includes bud-burst. 

We also need to include in initial growth those plant that (1) have new growth from existing stems or roots where the shoot system emerges from below ground and (2) new growth from seeds. We don't need to separate those two cases into separate classes, in order to map to NPN, but it still be a good idea for e.g., ag data where they track seed emergence. Also, for case (1), we cannot tell if the new growth is coming from a stem or root, so we only need to define it as new growth from below ground root or shoot during later growth cycle. 

Given our current mappings, I'm not sure that there is any value in distinguishing between new shoot systems that originate above ground and those that originate below, but again, it could be useful in the future for more detailed data collection.

Based on current understanding and our discussion way back when in Ft. Collins, I propose the following hierarchy for new growth:

initial growth present
>new above ground shoot-borne shoot system present
>>breaking buds present
>>(we could have a class for herbaceous above-ground shoot systems, but don't need it)
>new shoot system emerging from ground present
>> new shoot system emerging from ground in first growth cycle present (aka new seedling present)
>>new shoot system emerging from ground in later growth cycle present

All of the corresponding stages would end when the first leaf on the shoot system is unfolded. We don't need to worry too much about when they begin at this point, except for bud burst, which is already defined.

We could add another hierarchy for new shoot system presence in first versus later growth cycles, but I don't think we need it now.
