### ISSUE TITLE
Check definition of flower phenological stage, fresh flower, and fresh inflorescence

### ISSUE THREAD

**Issue by ramonawalls** [PlantPhenoOntology/ppo#43]
From Ellen: Completed floral organ senescence: In the {flower phenological stage} the definition says "...that has not yet begun {flower organ senescence}." I think we decided it was appropriate to change "begun" to "completed". Same for definitions of {fresh flower} and {fresh inflorescence}.

**Comment by robgur** [comment]
+1

**Comment by ramonawalls** [comment]
Current def. of flower phenological stage: A {plant phenological stage} in which the participant plant has at least one {flower bud} or {flower} that has not yet begun {floral organ senescence}.
New def:  A {plant phenological stage} in which the participant plant has at least one {flower bud} or {flower} that has not yet completed {floral organ senescence}.

Current def. of fresh flower: A {flower} that has not yet begun {floral organ senescence}
New def.: A {flower} that has not yet completed {floral organ senescence}.

Current def. of fresh inflorescence: An {inflorescence} that has not yet begun {floral organ senescence}
New def:. An {inflorescence} that has not yet completed {floral organ senescence}.

These traits don't yet have equivalency axioms, so changing the text definitions will not affect the ontology structure.

Changing the text definitions will automatically change the implications of the definitions of the corresponding traits, but should have no effect on reasoning.
