### ISSUE TITLE
leaf trait/stage name consistency

### ISSUE THREAD

**Issue by stuckyb** [PlantPhenoOntology/ppo#46]
Another naming consistency issue.  We have 'vascular leaf phenological stage', but the corresponding trait cluster is 'leaf presence', 'leaves absent', 'leaves present'.  We should probably use consistent naming for clarity.  Either use "vascular" in all four or don't use it in any.

**Comment by robgur** [comment]
I lean towards making explicit the term "vascular" for all.

**Comment by ramonawalls** [comment]
Using vascular in all would be consistent with PO. Longer labels, but I think we can live with that.

**Comment by stuckyb** [comment]
I made these changes with commit c79c90e, but now I wonder if the term we want to use is "true leaf", not "vascular leaf". "vascular leaf" includes cotyledons, and our stages and traits concern vascular leaves that are not cotyledons; i.e., true leaves.

**Comment by robgur** [comment]
Lets do "true leaf" -- I am convinced.
-r

**Comment by ramonawalls** [comment]
I'm okay with using true leaf, but Brian, as I am in the midst of editing, so please don't make any changes for the next few hours.

Also, if you changed all these labels, does that mean that all the definitions that use them have to change? I'm inclined to leave things as they are until we do the data ingest.

**Comment by stuckyb** [comment]
Okay, sounds good -- will switch to 'true leaf' at some point when 
Ramona's not making other changes.  Yes, if labels change, all the 
definitions that use them need to change, too, but OntoPilot will make 
sure that there are no "orphan" labels used anywhere.

**Comment by ramonawalls** [comment]
@stuckyb - I will not make any edits before Monday, so hack away at the labels!

**Comment by stuckyb** [comment]
Changed to "true leaf/leaves" with commit 52d618e.
