### ISSUE TITLE
Fix 'fruit ripe stage'

### ISSUE THREAD

**Issue by stuckyb** [PlantPhenoOntology/ppo#47]
Two fixes/questions:  First, I propose changing the definition from

> A 'fruit ripening stage' (PO:0025502) during which a single 'fruit' (PO:0009001) has progressed in the process of fruit ripening (GO:0009835) to the taxon-specific point at which it is widely considered by botanical experts to have seeds that are developed enough to be ready for dispersal, or in the case of agricultural crops, the fruit is considered palatable for human consumption.

to 

> A 'fruit ripening stage' (PO:0025502) during which a single 'fruit' (PO:0009001) has progressed in the process of fruit ripening (GO:0009835) to the taxon-specific point at which it is widely considered by botanical experts to have seeds that are developed enough to be ready for dispersal, or in the case of agricultural crops, the point at which the fruit is considered palatable for human consumption.

I think the latter is more grammatically correct.

Second, is 'fruit ripe stage' a proper subclass of 'fruit ripening stage'?  I wonder if the relationship is more part -> whole than it is subclass -> superclass.  I.e., is a 'fruit ripe stage' is *part of* some 'fruit ripening stage'?  The comment for 'fruit ripening stage' states that it "succeeds a fruit formation stage", but I'm not sure that is true for 'fruit ripe stage'.

**Comment by ramonawalls** [comment]
Good suggestions, I think we all agreed to delete this class in issue #49, so no need for the changes.

**Comment by stuckyb** [comment]
I'll delete this class and make the suggested changes in the definition for 'ripe fruit'.

**Comment by stuckyb** [comment]
Fixed with 5ca2949.
