### ISSUE TITLE
non-senescing leaf phenological stage logical definition

### ISSUE THREAD

**Issue by stuckyb** [PlantPhenoOntology/ppo#48]
Needs to be rewritten to reflect changes to the subclasses.

**Comment by ramonawalls** [comment]
+1

**Comment by stuckyb** [comment]
We've removed stages from the ontology, at least for the immediate future, so this is no longer relevant.  In general, the stages are thoroughly out of sync with the traits, and will need to be completely overhauled if/when we decide to return them to the PPO.
