### ISSUE TITLE
definition of 'ripe fruit'

### ISSUE THREAD

**Issue by stuckyb** [PlantPhenoOntology/ppo#49]
The definition of 'ripe fruit' is currently
> A 'ripening fruit' (PPO:0000210) that has completed ripening to the taxon-specific point at which it is widely considered by botanical experts to have seeds (PO:0009010) that are developed enough to be ready for dispersal, or, in the case of agricultural crops, the 'fruit' (PO:0009001) is considered palatable for human consumption.

This is just a copy (more or less) of the definition of 'fruit ripe stage'.  Copying definitions is not a good design because it makes it too easy for definitions to get out of sync.  I propose changing this to
> A 'fruit' (PO:0009001) that is participating in a 'fruit ripe stage' (PPO:0000224).

Alternatively, we could just delete the class 'fruit ripe stage' and only have 'ripe fruit' for now, since it is the only class that is actually used by the rest of the PPO.

**Comment by jdeck88** [comment]
+1 for deleting the "fruit ripe stage" if it is not used elsewhere.

**Comment by ramonawalls** [comment]
@stuckyb, your proposed changes to the definition of ripe fruit make perfect sense. I also agree that we should get rid of fruit ripe stage. Since we have not used it or released it yet, we can simply delete it, without using deprecation.

**Comment by stuckyb** [comment]
Fixed with 5ca2949.
