### ISSUE TITLE
Definition of 'ripe fruit phenological stage'

### ISSUE THREAD

**Issue by stuckyb** [PlantPhenoOntology/ppo#50]
The current definition is:
> A 'ripening fruit phenological stage' (PPO:0000104) in which the participant plant has at least one 'fruit' (PO:0009001) in the 'fruit ripe stage' (PPO:0000224).

I propose this be simplified to:
> A 'ripening fruit phenological stage' (PPO:0000104) in which the participant plant has at least one 'ripe fruit'.

**Comment by ramonawalls** [comment]
+1 !!

**Comment by stuckyb** [comment]
Fixed with 5ca2949.
