### ISSUE TITLE
Add classes for phenology characters from herbarium workshop

### ISSUE THREAD

**Issue by ramonawalls** [PlantPhenoOntology/ppo#6]
See list in progress: https://docs.google.com/spreadsheets/d/17CAVuH7DRufW1QHYk6cQf6IaHA-K1_2fuR0KCmWpO5Y/edit#gid=0

**Comment by stuckyb** [comment]
I took a brief look at that list, and I think everything on there is covered in at least some fashion by terms already in the PPO.  But I'll give a chance for others to double check before I close this issue.

**Comment by ramonawalls** [comment]
PPO still lacks terms for non-vascular leaf presence and for reproductive structure presence. We don't need these urgently, but will need them to map to this list. I suggest leaving this open for the time being, but marking it as low priority.

**Comment by ramonawalls** [comment]
Reproductive structure terms have been added, but we still lack terms for non-vascular leaves.

**Comment by ramonawalls** [comment]
I'm going to close this issue and make a separate one for non-vascular leaf presence.
