### ISSUE TITLE
Provide OBO export

### ISSUE THREAD

**Issue by cthoyt** [PlantPhenoOntology/ppo#63]
Hi, would you please provide an OBO export of this ontology? Thanks!

**Comment by ramonawalls** [comment]
I will add this as part of our ODK conversion.

**Comment by ramonawalls** [comment]
Fixed some time ago in https://github.com/PlantPhenoOntology/ppo/blob/odk-conversion/src/ontology/ppo-odk.yaml. Will show up in release.
