### ISSUE TITLE
problems with ontology IRI and version IRI

### ISSUE THREAD

**Issue by balhoff** [PlantPhenoOntology/ppo#65]
The OWL file at `http://purl.obolibrary.org/obo/ppo.owl` states its ontology IRI to be `https://raw.githubusercontent.com/PlantPhenoOntology/ppo/master/ppo.owl` and its version IRI to be `https://raw.githubusercontent.com/PlantPhenoOntology/ppo/master/releases/2018-10-26/ppo.owl`.

Ideally these would be `http://purl.obolibrary.org/obo/ppo.owl` and `http://purl.obolibrary.org/obo/ppo/releases/2018-10-26/ppo.owl`.

**Comment by ramonawalls** [comment]
I am going to convert PPO to use ODK. When I do so, I will fix that issue. Thanks, Jim.

**Comment by ramonawalls** [comment]
Fixed some time ago in https://github.com/PlantPhenoOntology/ppo/blob/odk-conversion/src/ontology/ppo-odk.yaml. Will show up in release.
