### ISSUE TITLE
Keep curies in definitions?

### ISSUE THREAD

**Issue by ramonawalls** [PlantPhenoOntology/ppo#67]
When we set up the PPO, we copied the then current practice of the PO of including term IDs (as CURIES) in the definitions. This is generally not done any more in obo ontologies. Should we get rid of them too? They don't really help with clarity.

For example:

A 'plant phenological trait' (PPO:0002000) that is measured by the number of some 'plant structure' (PO:0009011) that a 'whole plant' (PO:0000003) has abscised or that have been removed from a 'whole plant' (PO:0000003).

would change to

A 'plant phenological trait' that is measured by the number of some 'plant structure' that a 'whole plant' has abscised or that have been removed from a 'whole plant'.

@edenny, what do you think?

**Comment by edenny** [comment]
Fine with me if it goes away--I never used those numbers!

**Comment by ramonawalls** [comment]
They are removed from all terms being created in the ODK
