### ISSUE TITLE
DL to EL

### ISSUE THREAD

**Issue by stuckyb** [PlantPhenoOntology/PPO#7]
Decide how to capture count/cardinality (absence, in particular) information using the EL subset of OWL.

**Comment by stuckyb** [comment]
Before I close this, I wanted to check if everyone else agrees this is no longer an issue.

**Comment by ramonawalls** [comment]
Agree, no longer an issue.

**Comment by stuckyb** [comment]
Excellent.  Rob and John both weighed in via email, and they concur.
