### ISSUE TITLE
Add a wiki page to describe activities of herbarium workshop

### ISSUE THREAD

**Issue by ramonawalls** [PlantPhenoOntology/ppo#8]
Workshop wiki page: https://www.idigbio.org/wiki/index.php/Coding_Phenological_Data_from_Herbarium_Sheets

Wiki page should include workshop outcomes specific to PPO and links to some of the other material from the workshop.

**Comment by stuckyb** [comment]
@ramonawalls, is this still something that needs to be done?

**Comment by ramonawalls** [comment]
It seems like a good idea. I'll assign myself.

**Comment by ramonawalls** [comment]
This is not going to happen. Closing.
