### ISSUE TITLE
New count terms from herbarium sheets

### ISSUE THREAD

**Issue by ramonawalls** [PlantPhenoOntology/PPO#9]
- the number of complete individuals on the herbarium sheet
- the plant number, in sequence, for each of the plants recorded (e.g., if there were 3 plants on the sheet, the numbers 1, 2, and 3 appear in successive records)
- the number of buds on the plant (we counted buds that were > 5 mm in length)
- the number of open flowers (e.g., the tips of either stigmas or anthers had to be visible)
- the number of spent flowers, including both wilted flowers and those with expanding pistils
- the number of ripe fruits.  In these dry-fruited species, ripe fruits were identified as those that had begun to dehisce.

These are terms that Susan Mazer is gathering from herbarium data as part of the California Phenology Project.

**Comment by stuckyb** [comment]
Much of the above is now covered by terms in the PPO (counts related to numbers of flowers, ripening fruit, etc.).  Data specific to an herbarium sheet is not (yet?) in the PPO.  Is it still a goal to include that sort of information in the PPO?  To me, that kind of thing is in the realm of specimen/collection management (e.g., sheet identifiers, sheet metadata, specimen identifiers, etc.) and somewhat outside the PPO's concern.

**Comment by robgur** [comment]
Agree.  The metadata about the herbarium sheet itself is the realm of
Apple Core or some other endeavor.  Once can use PPO terms to annotate an
instance of flowering or fruiting on a herbarium sheet, right?

**Comment by stuckyb** [comment]
Correct, Rob, as long as you have an identifier for the sheet (or plant, if there are multiple plants on a sheet).  Information about how many plants are on a sheet, which plant matches up to which identifier, etc., seems to me broader than the domain of the PPO.

**Comment by robgur** [comment]
Agree.

**Comment by ramonawalls** [comment]
+1 I think you can close this.
