### ISSUE TITLE
Deprecate portion of plant

### ISSUE THREAD

**Issue by ramonawalls** [PlantPhenoOntology/ppo#92]
As per issue #85, if we are removing "portion of plant" from the definition of plant structure, we no longer need "portion of plant" (PPO:0001053). It was created to describe a proper part of a plant, which is problematic anyway.

**Comment by ramonawalls** [comment]
'Abscised plant structure present' include a clause for removed leaves:

An 'abscised plant structure presence' (PPO:0002002) trait that is a 'quality of' (RO:0000080) a 'whole plant' (PO:0000003) from which at least one of some 'plant structure' (PO:0009011) has been abscised **or removed**.

I think it may have been added to cover parts of plant in herbarium specimens or images. Does anyone (i.e. @edenny) know if it is included for another reason, such as to match a source definition? 

For ontological sake, I think it should be removed, because the equivalency axiom only includes the abscission relationship.

**Comment by edenny** [comment]
I am pretty sure we added this to cover the NPN phenophase "Falling leaves: One or more leaves with typical late-season color, or yellow or brown due to other stresses, are falling or have recently fallen from the plant."

**Comment by ramonawalls** [comment]
Also, abscised fruit or seed includes "has been abscised or removed by an herbivore" in the definition.

**Comment by edenny** [comment]
That was for the NPN phenophase "Recent fruit or seed drop: One or more mature fruits or seeds have dropped or been removed from the plant since your last visit."

**Comment by edenny** [comment]
We had to add that to our protocols especially for species where ripeness is defined by fruit/seed drop, such that observers may never be able to report seeing a ripe fruit attached to the plant.

**Comment by ramonawalls** [comment]
Thanks, Ellen! I will keep the definitions as they are, then.

**Comment by ramonawalls** [comment]
I am also deprecating the relation "is or was part of" since it was only used for this class.
